/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package hu.modeldriven.astah.matrix.ui;

/**
 * @author zsolt
 */
public class AbstractMatrixPanel extends javax.swing.JPanel {

    /**
     * Creates new form AbstractMatrixPanel
     */
    public AbstractMatrixPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPanel = new javax.swing.JPanel();
        rowElementTypeLabel = new javax.swing.JLabel();
        columnElementTypeLabel = new javax.swing.JLabel();
        rowTypeTextField = new javax.swing.JTextField();
        rowTypeSelectButton = new javax.swing.JButton();
        rowPackageLabel = new javax.swing.JLabel();
        rowPackageTextField = new javax.swing.JTextField();
        rowPackageSelectButton = new javax.swing.JButton();
        columnTypeTextField = new javax.swing.JTextField();
        columnTypeSelectButton = new javax.swing.JButton();
        columnPackageLabel = new javax.swing.JLabel();
        columnPackageTextField = new javax.swing.JTextField();
        columnPackageSelectButton = new javax.swing.JButton();
        dependencyTypeLabel = new javax.swing.JLabel();
        queryButton = new javax.swing.JButton();
        dependencyTextField = new javax.swing.JTextField();
        dependencySelectButton = new javax.swing.JButton();
        contentPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        matrixTable = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        topPanel.setBackground(new java.awt.Color(255, 255, 255));

        rowElementTypeLabel.setText("Row element type:");

        columnElementTypeLabel.setText("Column element type:");

        rowTypeTextField.setEnabled(false);

        rowTypeSelectButton.setText("Select...");

        rowPackageLabel.setText("Row package:");

        rowPackageTextField.setEnabled(false);

        rowPackageSelectButton.setText("Select...");

        columnTypeTextField.setEnabled(false);

        columnTypeSelectButton.setText("Select...");

        columnPackageLabel.setText("Column package:");

        columnPackageTextField.setEnabled(false);

        columnPackageSelectButton.setText("Select...");

        dependencyTypeLabel.setText("Dependency type:");

        queryButton.setText("Query");
        queryButton.setEnabled(false);

        dependencyTextField.setEnabled(false);

        dependencySelectButton.setText("Select...");

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
                topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(topPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(topPanelLayout.createSequentialGroup()
                                                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(rowElementTypeLabel)
                                                        .addComponent(rowPackageLabel)
                                                        .addComponent(dependencyTypeLabel))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(rowPackageTextField)
                                                        .addComponent(rowTypeTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                                        .addComponent(dependencyTextField))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(rowTypeSelectButton, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                                                        .addComponent(rowPackageSelectButton, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                                        .addComponent(dependencySelectButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                                                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topPanelLayout.createSequentialGroup()
                                                                .addComponent(columnElementTypeLabel)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(columnTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topPanelLayout.createSequentialGroup()
                                                                .addComponent(columnPackageLabel)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(columnPackageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(columnTypeSelectButton, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(columnPackageSelectButton, javax.swing.GroupLayout.Alignment.TRAILING)))
                                        .addGroup(topPanelLayout.createSequentialGroup()
                                                .addComponent(queryButton)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
        );

        topPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, rowPackageSelectButton, rowTypeSelectButton);

        topPanelLayout.setVerticalGroup(
                topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(topPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(rowElementTypeLabel)
                                        .addComponent(columnElementTypeLabel)
                                        .addComponent(rowTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(rowTypeSelectButton)
                                        .addComponent(columnTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(columnTypeSelectButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(columnPackageLabel)
                                        .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(rowPackageLabel)
                                                .addComponent(rowPackageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(rowPackageSelectButton)
                                                .addComponent(columnPackageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(columnPackageSelectButton)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(dependencyTypeLabel)
                                                .addComponent(dependencyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(dependencySelectButton))
                                .addGap(18, 18, 18)
                                .addComponent(queryButton)
                                .addContainerGap(18, Short.MAX_VALUE))
        );

        add(topPanel, java.awt.BorderLayout.NORTH);

        contentPanel.setLayout(new java.awt.BorderLayout());

        matrixTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{

                },
                new String[]{

                }
        ));
        jScrollPane1.setViewportView(matrixTable);

        contentPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(contentPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel columnElementTypeLabel;
    private javax.swing.JLabel columnPackageLabel;
    protected javax.swing.JButton columnPackageSelectButton;
    protected javax.swing.JTextField columnPackageTextField;
    protected javax.swing.JButton columnTypeSelectButton;
    protected javax.swing.JTextField columnTypeTextField;
    private javax.swing.JPanel contentPanel;
    protected javax.swing.JButton dependencySelectButton;
    protected javax.swing.JTextField dependencyTextField;
    private javax.swing.JLabel dependencyTypeLabel;
    private javax.swing.JScrollPane jScrollPane1;
    protected javax.swing.JTable matrixTable;
    protected javax.swing.JButton queryButton;
    private javax.swing.JLabel rowElementTypeLabel;
    private javax.swing.JLabel rowPackageLabel;
    protected javax.swing.JButton rowPackageSelectButton;
    protected javax.swing.JTextField rowPackageTextField;
    protected javax.swing.JButton rowTypeSelectButton;
    protected javax.swing.JTextField rowTypeTextField;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables
}
